Doc: pooch install for xarray dataset
observingClouds/xbitinfo pull request #185
Opened 2023-04-04 03:27 UTC by Ishaanj18

[As specified here](https://github.com/observingClouds/xbitinfo/pull/184#issuecomment-1495225718)

2023-04-04 06:23 UTC, observingClouds requested changes
If you could undo the two additions of `\n` we should be good to merge this PR.

2023-04-04 06:23 UTC, observingClouds commented on docs/quick-start.ipynb
> +    "xb.plot_distribution(ds)\n",
I think this got in here by accident. Could you undo this to the original version?

2023-04-04 06:23 UTC, observingClouds commented on docs/quick-start.ipynb
> +    "## Visualize information content\n",
Same as above

2023-04-04 17:34 UTC, ayoubft commented
Dear @Ishaanj18 ,

I am writing to express my frustration regarding this pull request.  I made an effort to start the other PR, and **observingClouds** suggested adding this to the docs. I wanted to implement that, only to find that you had already made those changes.

While I understand that you are keen to contribute, and take the initiative, but not like this. Similar behavior can make it for starters like me very difficult to feel motivated to contribute.

I believe that collaborative work should involve clear communication and mutual respect.

2023-04-14 05:31 UTC, Ishaanj18 commented
Really sorry for the inconvenience that I have caused, even I am new to open source contribution. It has been pointed out to me now that the cooldown period for open source is 2 weeks. I made the request as there had been no updates/changes made on the prior PR and had been marked as closed. I will keep this in mind in future.
Looking forward to collaborating with you.
Regards

2023-04-29 13:51 UTC, ayoubft commented
Hi @Ishaanj18,
No worries, I understand. The issue was not yet stale, but I appreciate your apology. I'm looking forward to collaborating with you too.
Thanks

2023-05-26 05:06 UTC, observingClouds approved these changes

2023-05-26 05:25 UTC, merged